// Generated by tools/generate_seedfx_catalog.py; append-only parameter ABI.
#pragma once
#include "seedfx_catalog.h"
typedef struct {
    uint16_t type;
    uint8_t index;
    SeedFxParameterDescriptor parameter;
} SeedFxExtension;
static const SeedFxExtension seedfx_extensions[] = {
    {2, 1, {"Balance", "%", -1.0f, 1.0f, 0.01f, 0.0f}},
    {5, 2, {"Level", "%", 0.0f, 1.5f, 0.01f, 1.0f}},
    {6, 2, {"Mix", "%", 0.0f, 1.0f, 0.01f, 1.0f}},
    {9, 2, {"Level", "%", 0.0f, 1.5f, 0.01f, 1.0f}},
    {19, 2, {"Input", "dB", -18.0f, 18.0f, 0.5f, 0.0f}},
    {20, 2, {"Attack", "ms", 1.0f, 100.0f, 1.0f, 1.0f}},
    {24, 3, {"Tone", "%", 0.0f, 1.0f, 0.01f, 1.0f}},
    {25, 3, {"Tone", "%", 0.0f, 1.0f, 0.01f, 1.0f}},
    {26, 3, {"Tone", "%", 0.0f, 1.0f, 0.01f, 1.0f}},
    {27, 3, {"Stereo", "%", 0.0f, 1.0f, 0.01f, 1.0f}},
    {29, 2, {"Mix", "%", 0.0f, 1.0f, 0.01f, 1.0f}},
    {32, 1, {"Balance", "%", -1.0f, 1.0f, 0.01f, 0.0f}},
    {36, 3, {"Decay", "%", 0.0f, 0.92f, 0.01f, 0.675f}},
    {37, 2, {"Mix", "%", 0.0f, 1.0f, 0.01f, 1.0f}},
};
static inline void seedfx_extend_catalog(SeedFxCatalogEntry *entry)
{
    for (unsigned i = 0; i < sizeof(seedfx_extensions) / sizeof(seedfx_extensions[0]); ++i) {
        const SeedFxExtension *ext = &seedfx_extensions[i];
        if (ext->type == entry->effect_type && entry->parameter_count == ext->index) {
            entry->parameters[ext->index] = ext->parameter;
            ++entry->parameter_count;
        }
    }
}
static inline void seedfx_extension_defaults(uint16_t type, float *values, unsigned count)
{
    for (unsigned i = 0; i < sizeof(seedfx_extensions) / sizeof(seedfx_extensions[0]); ++i) {
        const SeedFxExtension *ext = &seedfx_extensions[i];
        if (ext->type == type && count <= ext->index)
            values[ext->index] = ext->parameter.default_value;
    }
}
